Depart from ND-GAIN Dataset from the Notre Dame Global Adaptation Initiative

In [0]:
# Content: climate vulnerability and readiness scores for 180 countries between 1995-2023 according to Notre Dame Global Adaptation Initiative methodology, compound indices with separate indicators available.
# Source: https://gain.nd.edu/our-work/country-index/download-data/

In [0]:
import pandas as pd
ready_raw = pd.read_csv('/Workspace/Users/nelemaktas@gmail.com/Midterm assignment Nele Aktas/readiness.csv')
vuln_raw = pd.read_csv('/Workspace/Users/nelemaktas@gmail.com/Midterm assignment Nele Aktas/vulnerability.csv')
ready_raw.head()

  ISO3         Name      1995      1996  ...      2020      2021      2022      2023
0  AFG  Afghanistan  0.309691  0.309690  ...  0.236749  0.246106  0.249550  0.251374
1  ALB      Albania  0.332968  0.333487  ...  0.407430  0.412306  0.418177  0.422698
2  DZA      Algeria  0.300272  0.301323  ...  0.325523  0.329650  0.337037  0.345662
3  AND      Andorra  0.123870  0.126191  ...  0.348305  0.350802  0.391279  0.452459
4  AGO       Angola  0.190434  0.190433  ...  0.260653  0.267595  0.271751  0.272532

[5 rows x 31 columns]

In [0]:
vuln_raw.head()

  ISO3         Name      1995      1996  ...      2020      2021      2022      2023
0  AFG  Afghanistan  0.612511  0.612679  ...  0.582315  0.586000  0.587796  0.587516
1  ALB      Albania  0.451827  0.452691  ...  0.395254  0.383450  0.380609  0.380184
2  DZA      Algeria  0.398323  0.397332  ...  0.358463  0.369852  0.367361  0.367352
3  AND      Andorra       NaN       NaN  ...       NaN       NaN       NaN       NaN
4  AGO       Angola  0.493885  0.494235  ...  0.513685  0.510007  0.508757  0.506373

[5 rows x 31 columns]

In [0]:
print(f"No. countries in readiness index: {ready_raw['ISO3'].nunique()}")
print(f"No. countries in vulnerability index: {vuln_raw['ISO3'].nunique()}")

No. countries in readiness index: 192
No. countries in vulnerability index: 192

In [0]:
# For each dataset, restrict to 2023, rename columns
vuln_2023 = vuln_raw[['ISO3','Name','2023']]
vuln_2023 = vuln_2023.rename(columns={'2023': 'vulnerability_score'})
vuln_2023.head()

ready_2023 = ready_raw[['ISO3','2023']]
ready_2023 = ready_2023.rename(columns={'2023': 'readiness_score'})
ready_2023.head()

  ISO3  readiness_score
0  AFG         0.251374
1  ALB         0.422698
2  DZA         0.345662
3  AND         0.452459
4  AGO         0.272532

In [0]:
ready_2023 = ready_2023.dropna(subset=['readiness_score'])
vuln_2023 = vuln_2023.dropna(subset=['vulnerability_score'])

ready_2023[ready_2023['readiness_score'].isna()]
#vuln_2023[vuln_2023['vulnerability_score'].isna()]

Empty DataFrame
Columns: [ISO3, readiness_score]
Index: []

In [0]:
ready_2023['readiness_score'].describe()

count    192.000000
mean       0.429514
std        0.140339
min        0.132553
25%        0.321631
50%        0.418369
75%        0.524132
max        0.800124
Name: readiness_score, dtype: float64

In [0]:
vuln_2023['vulnerability_score'].describe()

count    187.000000
mean       0.432774
std        0.092297
min        0.251258
25%        0.364166
50%        0.421516
75%        0.507753
max        0.639627
Name: vulnerability_score, dtype: float64

In [0]:
merged_2023 = ready_2023.merge(vuln_2023, on='ISO3', how='inner')
merged_2023 = merged_2023[['ISO3', 'Name', 'vulnerability_score','readiness_score']]
print(f"{merged_2023.head()}")
print(f"{merged_2023.shape}")

  ISO3                 Name  vulnerability_score  readiness_score
0  AFG          Afghanistan             0.587516         0.251374
1  ALB              Albania             0.380184         0.422698
2  DZA              Algeria             0.367352         0.345662
3  AGO               Angola             0.506373         0.272532
4  ATG  Antigua and Barbuda             0.467682         0.448599
(187, 4)

In [0]:
import plotly.express as px

fig = px.scatter(
    merged_2023,
    x='vulnerability_score',
    y='readiness_score',
    size='vulnerability_score',
    color='readiness_score',
    hover_name='Name',
    title='Climate risk: Vulnerability vs Readiness (2023)'
)
fig.show()

In [0]:
ready_2023_sorted = ready_2023.sort_values('readiness_score',ascending=False)
ready_2023_sorted

    ISO3  readiness_score
154  SGP         0.800124
46   DNK         0.765320
128  NOR         0.764781
58   FIN         0.745595
89   KOR         0.727000
..   ...              ...
39   COD         0.214130
54   ERI         0.213409
187  VEN         0.191711
33   TCD         0.186652
32   CAF         0.132553

[192 rows x 2 columns]

In [0]:
vuln_2023_sorted = vuln_2023.sort_values('vulnerability_score',ascending=False)
vuln_2023_sorted

    ISO3                             Name  vulnerability_score
33   TCD                             Chad             0.639627
126  NER                            Niger             0.632981
157  SLB                  Solomon Islands             0.629253
112  FSM  Micronesia, Federated States of             0.621189
69   GNB                    Guinea-Bissau             0.612813
..   ...                              ...                  ...
30   CAN                           Canada             0.281584
58   FIN                          Finland             0.280200
45   CZE                   Czech Republic             0.263809
128  NOR                           Norway             0.255615
166  CHE                      Switzerland             0.251258

[187 rows x 3 columns]

Include income group classification dataset

In [0]:
## Content: World Bank classification of countries into income groups using GNI per capita and Atlas method. Published yearly on 1st July.
## Classification:
#   L (Low income) <= 1,145LM (Lower middle income) 1,146 - 4,515
#   UM (Upper middle income) 4,516 - 14,005
#   H (High income) > 14,005
# Source: https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups

In [0]:
# Using AI for debugging, I found out that I needed openpyxl in order to work with an excel file (xlsx)
%pip install openpyxl

Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-c680c1fa-936a-4b67-86ac-6f63552c9453/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-c680c1fa-936a-4b67-86ac-6f63552c9453/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
# Import dataset
income_raw = pd.read_excel('/Workspace/Users/nelemaktas@gmail.com/Midterm assignment Nele Aktas/Country income groups World Bank edited.xlsx')
income_raw.head()

  Country Code            Name 1987 1988 1989  ... 2020 2021 2022 2023 2024
0          AFG     Afghanistan    L    L    L  ...    L    L    L    L    L
1          ALB         Albania   ..   ..   ..  ...   UM   UM   UM   UM   UM
2          DZA         Algeria   UM   UM   LM  ...   LM   LM   LM   UM   UM
3          ASM  American Samoa    H    H    H  ...   UM   UM    H    H    H
4          AND         Andorra   ..   ..   ..  ...    H    H    H    H    H

[5 rows x 40 columns]

In [0]:
# Bring to similar format as dataset on climate risk
income = income_raw[['Country Code',2023]]
income = income.rename(columns={'Country Code':'ISO3',2023:'Income group'})
income = income.dropna(subset="Income group")
print(f"{income.head()}")
print(f"{income.shape}")

  ISO3 Income group
0  AFG            L
1  ALB           UM
2  DZA           UM
3  ASM            H
4  AND            H
(217, 2)

In [0]:
merged_2023_income = merged_2023.merge(income, on='ISO3', how='inner')
merged_2023_income.head()

  ISO3                 Name  vulnerability_score  readiness_score Income group
0  AFG          Afghanistan             0.587516         0.251374            L
1  ALB              Albania             0.380184         0.422698           UM
2  DZA              Algeria             0.367352         0.345662           UM
3  AGO               Angola             0.506373         0.272532           LM
4  ATG  Antigua and Barbuda             0.467682         0.448599            H

In [0]:
fig = px.scatter(
    merged_2023,
    x='vulnerability_score',
    y='readiness_score',
    size='vulnerability_score',
    color='readiness_score',
    hover_name='Name',
    title='Climate risk: Vulnerability vs Readiness (2023)'
)
fig.show()

Include GDP data

In [0]:
## Content: GDP in current prices (dollar)
## Source: https://data.worldbank.org/indicator/NY.GDP.MKTP.CD
# First 4 rows are metadata

In [0]:
gdp_raw = pd.read_csv('/Workspace/Users/nelemaktas@gmail.com/Midterm assignment Nele Aktas/GDP data number format edited new.csv')
gdp_raw.head()

                  Country Name Country Code  ...          2024 2025
0                        Aruba          ABW  ...  4.265651e+09  NaN
1  Africa Eastern and Southern          AFE  ...  1.242694e+12  NaN
2                  Afghanistan          AFG  ...           NaN  NaN
3   Africa Western and Central          AFW  ...  7.363850e+11  NaN
4                       Angola          AGO  ...  1.009989e+11  NaN

[5 rows x 70 columns]

In [0]:
# Reduce to relevant columns, drop rows with missing values, rename columns in accord with dataset on climate risk
gdp = gdp_raw[['Country Code','2023']]
gdp = gdp.rename(columns={'Country Code':'ISO3', '2023':'GDP'})
gdp = gdp.dropna(subset="GDP")
print(gdp.head())
print(gdp.shape)
print(gdp['ISO3'].unique())

  ISO3           GDP
0  ABW  3.834730e+09
1  AFE  1.179359e+12
2  AFG  1.715223e+10
3  AFW  9.382384e+11
4  AGO  1.071677e+11
(251, 2)
['ABW' 'AFE' 'AFG' 'AFW' 'AGO' 'ALB' 'AND' 'ARB' 'ARE' 'ARG' 'ARM' 'ATG'
 'AUS' 'AUT' 'AZE' 'BDI' 'BEL' 'BEN' 'BFA' 'BGD' 'BGR' 'BHR' 'BHS' 'BIH'
 'BLR' 'BLZ' 'BMU' 'BOL' 'BRA' 'BRB' 'BRN' 'BTN' 'BWA' 'CAF' 'CAN' 'CEB'
 'CHE' 'CHI' 'CHL' 'CHN' 'CIV' 'CMR' 'COD' 'COG' 'COL' 'COM' 'CPV' 'CRI'
 'CSS' 'CUW' 'CYM' 'CYP' 'CZE' 'DEU' 'DJI' 'DMA' 'DNK' 'DOM' 'DZA' 'EAP'
 'EAR' 'EAS' 'ECA' 'ECS' 'ECU' 'EGY' 'EMU' 'ESP' 'EST' 'ETH' 'EUU' 'FCS'
 'FIN' 'FJI' 'FRA' 'FRO' 'FSM' 'GAB' 'GBR' 'GEO' 'GHA' 'GIN' 'GMB' 'GNB'
 'GNQ' 'GRC' 'GRD' 'GRL' 'GTM' 'GUY' 'HIC' 'HKG' 'HND' 'HPC' 'HRV' 'HTI'
 'HUN' 'IBD' 'IBT' 'IDA' 'IDB' 'IDN' 'IDX' 'IND' 'IRL' 'IRN' 'IRQ' 'ISL'
 'ISR' 'ITA' 'JAM' 'JOR' 'JPN' 'KAZ' 'KEN' 'KGZ' 'KHM' 'KIR' 'KNA' 'KOR'
 'KWT' 'LAC' 'LAO' 'LBN' 'LBR' 'LBY' 'LCA' 'LCN' 'LDC' 'LIC' 'LIE' 'LKA'
 'LMC' 'LMY' 'LSO' 'LTE' 'LTU' 'LUX' 'LVA' 'MAC' 'MAR' 'MCO' 'MDA' 'MDG'
 'MDV' 'MEA' 'MEX' 'MHL' 'MIC' 'MKD' 'MLI' 'MLT' 'MMR' 'MNA' 'MNE' 'MNG'
 'MOZ' 'MRT' 'MUS' 'MWI' 'MYS' 'NAC' 'NAM' 'NCL' 'NER' 'NGA' 'NIC' 'NLD'
 'NOR' 'NPL' 'NRU' 'NZL' 'OED' 'OMN' 'OSS' 'PAK' 'PAN' 'PER' 'PHL' 'PLW'
 'PNG' 'POL' 'PRE' 'PRI' 'PRT' 'PRY' 'PSE' 'PSS' 'PST' 'PYF' 'QAT' 'ROU'
 'RUS' 'RWA' 'SAS' 'SAU' 'SDN' 'SEN' 'SGP' 'SLB' 'SLE' 'SLV' 'SMR' 'SOM'
 'SRB' 'SSA' 'SSF' 'SST' 'STP' 'SUR' 'SVK' 'SVN' 'SWE' 'SWZ' 'SXM' 'SYC'
 'TCA' 'TCD' 'TEA' 'TEC' 'TGO' 'THA' 'TJK' 'TKM' 'TLA' 'TLS' 'TMN' 'TON'
 'TSA' 'TSS' 'TTO' 'TUN' 'TUR' 'TUV' 'TZA' 'UGA' 'UKR' 'UMC' 'URY' 'USA'
 'UZB' 'VCT' 'VEN' 'VNM' 'VUT' 'WLD' 'WSM' 'XKX' 'ZAF' 'ZMB' 'ZWE']

In [0]:
merged_2023_income_gdp = merged_2023_income.merge(gdp, on='ISO3', how='inner')
merged_2023_income_gdp.head()

  ISO3                 Name  ...  Income group           GDP
0  AFG          Afghanistan  ...             L  1.715223e+10
1  ALB              Albania  ...            UM  2.349124e+10
2  DZA              Algeria  ...            UM  2.479239e+11
3  AGO               Angola  ...            LM  1.071677e+11
4  ATG  Antigua and Barbuda  ...             H  2.005785e+09

[5 rows x 6 columns]

In [0]:
merged_2023_income_gdp.columns

Index(['ISO3', 'Name', 'vulnerability_score', 'readiness_score',
       'Income group', 'GDP'],
      dtype='object')

In [0]:
# Change names of income groups for better comprehension
merged_2023_income_gdp['Income group'] = merged_2023_income_gdp['Income group'].replace({
    'L': 'Low income',
    'LM': 'Lower-middle income',
    'UM': 'Upper-middle income',
    'H': 'High income'
})

In [0]:
# Update scatter plot with GDP as scatter size
fig1 = px.scatter(
    merged_2023_income_gdp,
    x='vulnerability_score',
    y='readiness_score',
    size='GDP',
    title='The most vulnerable countries are the least able to cope with climate change',
    labels={
        'vulnerability_score': 'Vulnerability Score',
        'readiness_score': 'Readiness Score'},
    category_orders={
        'Income group': ['Low income', 'Lower-middle income', 'Upper-middle income', 'High income']},
    color='Income group',
    color_discrete_map={
        'Low income': '#e74c3c','Lower-middle income': '#f39c12','Upper-middle income': '#f1c40f','High income': '#27ae60'},
    template='plotly_white', # for better data-ink-ratio
    hover_name='Name',
    size_max=90)
fig1.show()

In [0]:
# Label intersting countries (identified by looking at the plot and using the table of the climate risk index)

fig2 = px.scatter(
    merged_2023_income_gdp,
    x='vulnerability_score',
    y='readiness_score',
    size='GDP',
    title='The countries most vulnerable to climate change are the least able to cope with it',
    labels={
        'vulnerability_score': 'Vulnerability Score',
        'readiness_score': 'Readiness Score'},
    category_orders={
        'Income group': ['Low income', 'Lower-middle income', 'Upper-middle income', 'High income']},
    color='Income group',
    color_discrete_map={
        'Low income': '#e74c3c','Lower-middle income': '#f39c12','Upper-middle income': '#f1c40f','High income': '#27ae60'},
    template='plotly_white', # for better data-ink-ratio
    opacity=0.5, # for better visibility
    hover_name='Name',
    size_max=90)

interesting_countries = ['Norway', 'Chad', 'Singapore', 'Switzerland','Rwanda','Kyrgyzstan','Turkmenistan','Somalia']

for country in interesting_countries:
    point = merged_2023_income_gdp[merged_2023_income_gdp['Name'] == country].iloc[0]
    fig2.add_annotation(
        x=point['vulnerability_score'],
        y=point['readiness_score'],
        text=country,
        showarrow=True)
    
fig2.show()